ARG TRAEFIK_VERSION=3.5

FROM traefik:$TRAEFIK_VERSION

COPY ./layouts/ /etc/traefik/

RUN set -eux \
    # Register Root CA \
    && cp /etc/traefik/ssl.d/root/certificate.pem /etc/ssl/certs/Crasivo_Root_CA.crt \
    && update-ca-certificates

WORKDIR /etc/traefik

HEALTHCHECK \
    --interval=10s \
    --timeout=3s \
    --start-period=3s \
    --retries=5 \
    CMD traefik healthcheck --ping || exit 1

EXPOSE 80 443
