# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Example configuration for Traefik v3
# ----------------------------------------------------------------
# $ docker network create -d bridge traefik_public
# $ docker compose -f docker-compose.example.yml up -d
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

name: traefik

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - "TRAEFIK_VERSION=3.5"
    container_name: traefik
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1G
    hostname: traefik
    networks:
      - public
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      # HTTP route (with redirect)
      - "traefik.http.routers.traefik-api-http.rule=Host(`${TRAEFIK_API_HOST:-traefik.docker}`) || Host(`localhost`)"
      - "traefik.http.routers.traefik-api-http.entryPoints=http"
      - "traefik.http.routers.traefik-api-http.middlewares=redirect-to-https@file"
      # HTTPS route
      - "traefik.http.routers.traefik-api-https.rule=Host(`${TRAEFIK_API_HOST:-traefik.docker}`) || Host(`localhost`)"
      - "traefik.http.routers.traefik-api-https.entryPoints=https"
      - "traefik.http.routers.traefik-api-https.tls=true"
      - "traefik.http.routers.traefik-api-https.service=api@internal"

networks:
  public:
    external: true
    name: traefik_public
