http:
  middlewares:
    # Cloudflare IPv4 whitelist (https://www.cloudflare.com/ips-v4)
    cloudflare-ipv4-whitelist:
      ipWhiteList:
        sourceRange:
          - 173.245.48.0/20
          - 103.21.244.0/22
          - 103.22.200.0/22
          - 103.31.4.0/22
          - 141.101.64.0/18
          - 108.162.192.0/18
          - 190.93.240.0/20
          - 188.114.96.0/20
          - 197.234.240.0/22
          - 198.41.128.0/17
          - 162.158.0.0/15
          - 104.16.0.0/12
          - 172.64.0.0/13
          - 131.0.72.0/22
    # Local whitelist
    local-ipv4-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 100.64.0.0/10
          - 127.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
    security-headers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
          server: ''
          X-Forwarded-Proto: https
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: strict-origin-when-cross-origin
        hostsProxyHeaders:
          - X-Forwarded-Host
        customRequestHeaders:
          X-Forwarded-Proto: https
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    redirect-to-wss:
      redirectScheme:
        scheme: wss
        permanent: true
