tls:
  options:
    default:
      minVersion: VersionTLS12
  certificates:
    - certFile: /etc/traefik/ssl.d/localhost/certificate_fullchain.pem
      keyFile: /etc/traefik/ssl.d/localhost/private_key.pem
    - certFile: /etc/traefik/ssl.d/traefik_docker/certificate_fullchain.pem
      keyFile: /etc/traefik/ssl.d/traefik_docker/private_key.pem
    - certFile: /etc/traefik/ssl.d/traefik_internal/certificate_fullchain.pem
      keyFile: /etc/traefik/ssl.d/traefik_internal/private_key.pem
    - certFile: /etc/traefik/ssl.d/traefik_local/certificate_fullchain.pem
      keyFile: /etc/traefik/ssl.d/traefik_local/private_key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/ssl.d/traefik_default/certificate_fullchain.pem
        keyFile: /etc/traefik/ssl.d/traefik_default/private_key.pem
