# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Basic configuration for Traefik v3.x
# --------------------------------------------------------------------------------
# Environments: https://doc.traefik.io/traefik/reference/static-configuration/env/
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# ----------------------------------------------------------------
# Global
# ----------------------------------------------------------------

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# ----------------------------------------------------------------
# Entrypoints
# ----------------------------------------------------------------

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

# ----------------------------------------------------------------
# API
# ----------------------------------------------------------------

api:
  dashboard: true
  debug: false
  insecure: true

ping:
  entryPoint: traefik

# ----------------------------------------------------------------
# Logging
# ----------------------------------------------------------------

log:
  filePath: /dev/stdout
  format: common
  level: info

# ----------------------------------------------------------------
# Certificate resolvers
# ----------------------------------------------------------------

certificatesResolvers:
  letsencrypt:
    acme:
      email: webmaster@traefik.docker # change me
      storage: /etc/traefik/acme-letsencrypt.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
      tlsChallenge: {}

# ----------------------------------------------------------------
# Providers
# ----------------------------------------------------------------

providers:
  providersThrottleDuration: 10s
  # https://doc.traefik.io/traefik/providers/file/
  file:
    directory: /etc/traefik/conf.d
    watch: true
  # https://doc.traefik.io/traefik/providers/docker/
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik_public
